### ISSUE TITLE
States blocks fakeplayers from working.

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/States#10]
While states is active, and protecting a chunk that my Ancient Warfare tree farm is in, it is blocked from doing work.

See this comment from Lexmanos about how blocks placed by the player are flagged as being owned by a player, and you can block based on the player that placed them.

https://github.com/ldtteam/minecolonies/issues/645

**Comment by Fexcraft** [comment]
I do not see anywhere a mention about blocks being flagged as owned?
As far I understand there is something in the other mod that marks stuff of that mod.

**Comment by Fexcraft** [comment]
Last I recall on this topic, one issue might be that AW used the same "playername" for the FakePlayer for every interaction, so even if it would work... it would be registered as the same UUID/Player.

But I recall I couldn't even get testing that far due to nullpointers,
of which I couldn't find out the source of back then.
